name: CI/CD Pipeline

permissions:
  contents: 'read'
  id-token: 'write'
  actions: 'read'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build project
        run: ./gradlew build

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew cucumberCli

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker build --tag=string-service:latest .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/133370309179/locations/global/workloadIdentityPools/beluga-wif-pool/providers/beluga-wif-provider'
          service_account: 'beluga-terraform-challenge-del@gcp-it-ls-beluga-drddev-yy.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform plan -no-color
          terraform apply
